### ISSUE TITLE
Add support for snapshot auto-deletion

### ISSUE THREAD

**Issue by farzawm03** [jrabinow/snapper-rollback#13]
hello guys, this isnt actually a bug, and sorry for getting in your hair and everything, what you made is a masterpiece, i had a question, maybe suggestion, after rolling back, why are the old subvols left? is this intended? perhaps an option to run it Clean or sth would be nice so you dont have to manually mount and delete again? now i know its 20 second work to mount and delete the subvols but i just thought that would be a cool addition to your progeam, and perhaps more noob friendly and more useful on longterm... thank you

**Comment by jrabinow** [comment]
hey @farzawm03 thanks for providing feedback, always!
The script stands on the shoulders of giants, [btrfs](https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/), [OpenSUSE's snapper tool](https://en.opensuse.org/openSUSE:Snapper_Tutorial) and the [archlinux community](https://wiki.archlinux.org/title/Snapper) just to name a few, I'm glad you like it.

> why are the old subvols left? is this intended?
When this script is called, it's quite possible that the system is borked but that the operator made some changes since the snapshot they're rolling back to. Keeping the pre-rollback snapshot available allows the operator to go back once the system is back online and recover whatever files they'd like, as well as potentially troubleshoot why their system got borked in the first place.

If you're using this script with a different usecase in mind - which one? - I think we could talk about adding a flag along the lines of `--no-current-system-snapshot-warning-permanent-data-deletion` (intentionally long and verbose to avoid accidents). Would that be of interest? Do you think you'd be able to implement this enhancement?

**Comment by jrabinow** [comment]
hey @farzawm03 thanks for providing feedback, always!
The script stands on the shoulders of giants, [btrfs](https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/), [OpenSUSE's snapper tool](https://en.opensuse.org/openSUSE:Snapper_Tutorial) and the [archlinux community](https://wiki.archlinux.org/title/Snapper) just to name a few, I'm glad you like it.

> why are the old subvols left? is this intended?

When this script is called, it's quite possible that the system is borked but that the operator made some changes since the snapshot they're rolling back to. Keeping the pre-rollback snapshot available allows the operator to go back once the system is back online and recover whatever files they'd like, as well as potentially troubleshoot why their system got borked in the first place.

If you're using this script with a different usecase in mind - which one? - I think we could talk about adding a flag along the lines of `--no-current-system-snapshot-warning-permanent-data-deletion` (intentionally long and verbose to avoid accidents). Would that be of interest? Do you think you'd be able to implement this enhancement?

**Comment by farzawm03** [comment]
hello, that sounds great, sadly i know nothing of python, im going to perhaps implement my own bash script (which is not going to be the best) im actually a junior sysadmin so do not expect much... im still gonna give it a try tho as i need a better solution than mounting and removing manually (who knows what if i remove sth false...) so yea ill let you know if i have something of value, its gonna be in bash tho, although i do not imagine it being hard to just link it into the script..., thank you anyways for this wonderful script, rolled backed quite a few times already, i donot understand why the built in snapper rollback isnt as handy as this, perhaps you could offer them to build your script in their package? anyways, thanks again.

**Comment by jrabinow** [comment]
Adding this to the main snapper package would be problematic. This script assumes a very specific partition layout, snapper can't do that.
You're welcome! I'm glad it helped you out. I'm going to close this issue as adding a bash wrapper script for snapper-rollback seems to be out of scope for the project. However if you have a feature in mind, feel free to reopen
